apiVersion: v1
kind: Pod
metadata:
  name: node-api-pod
spec:
  containers:
    - image: nodejs-demo-image
      name: node-api
      imagePullPolicy: IfNotPresent
      resources: {}
      ports:
        - containerPort: 3000