apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  labels:
    run: nodeapi
spec:
  type: NodePort
  ports:
  - targetPort: 3000
    port: 4000
    nodePort: 30000
    protocol: TCP
  selector:
    app: nodeapi